version: '3.9'
services:
  app:
    build: .
    container_name: example-template
    image: example-template
    env_file:
      - ./config/.env
    ports:
      - "8080:8080"
    network_mode: "host"