// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: otherService.proto

package otherService

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// OtherServiceClient is the client API for OtherService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OtherServiceClient interface {
	Process(ctx context.Context, in *ProcessRequest, opts ...grpc.CallOption) (*ProcessResponse, error)
}

type otherServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOtherServiceClient(cc grpc.ClientConnInterface) OtherServiceClient {
	return &otherServiceClient{cc}
}

func (c *otherServiceClient) Process(ctx context.Context, in *ProcessRequest, opts ...grpc.CallOption) (*ProcessResponse, error) {
	out := new(ProcessResponse)
	err := c.cc.Invoke(ctx, "/otherService.otherService/Process", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OtherServiceServer is the server API for OtherService service.
// All implementations must embed UnimplementedOtherServiceServer
// for forward compatibility
type OtherServiceServer interface {
	Process(context.Context, *ProcessRequest) (*ProcessResponse, error)
	mustEmbedUnimplementedOtherServiceServer()
}

// UnimplementedOtherServiceServer must be embedded to have forward compatible implementations.
type UnimplementedOtherServiceServer struct {
}

func (UnimplementedOtherServiceServer) Process(context.Context, *ProcessRequest) (*ProcessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Process not implemented")
}
func (UnimplementedOtherServiceServer) mustEmbedUnimplementedOtherServiceServer() {}

// UnsafeOtherServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OtherServiceServer will
// result in compilation errors.
type UnsafeOtherServiceServer interface {
	mustEmbedUnimplementedOtherServiceServer()
}

func RegisterOtherServiceServer(s grpc.ServiceRegistrar, srv OtherServiceServer) {
	s.RegisterService(&OtherService_ServiceDesc, srv)
}

func _OtherService_Process_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OtherServiceServer).Process(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/otherService.otherService/Process",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OtherServiceServer).Process(ctx, req.(*ProcessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OtherService_ServiceDesc is the grpc.ServiceDesc for OtherService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OtherService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "otherService.otherService",
	HandlerType: (*OtherServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Process",
			Handler:    _OtherService_Process_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "otherService.proto",
}
